### ISSUE TITLE
Can you please change the name of repository

### ISSUE THREAD

**Issue by GermanBluefox** [soef/ioBroker.wm-bus#1]
iobroker => ioBroker

For all yours repositories.

**Comment by soef** [comment]
I know you've asked this before. I know that this is importand. Where is the show-name necessary?

**Comment by GermanBluefox** [comment]
Actually, it is not important. But historically all adapter's repositories
have such name.

Am 16.11.2016 23:09 schrieb "soef" notifications@github.com:

**Comment by soef** [comment]
Done :-)
