### ISSUE TITLE
Also use this adapter for "wired mbus"?

### ISSUE THREAD

**Issue by Apollon77** [soef/ioBroker.wm-bus#15]
Hey, Would this be possible too? befause the protocol itself should be compatible or ?!

**Comment by soef** [comment]
Hi, I think the m-bus protocol is not the same than the wm-bus. I can not test it, because I have no wired device. If you get the wired m-bus data to the serial port, you can test it.

**Comment by Apollon77** [comment]
The protocol should be comparable, latest when it comes to payload :-)
I found some mbus testframes at https://github.com/samkrew/libmbus/tree/master/test/test-frames ... and tried to put them into your wmbus lib, but was not that successfull because Link layer is different. With Application layer it should start to be same. 
www.m-bus.com/files/MBDOC48.PDF

**Comment by Apollon77** [comment]
You are right. Too many differences. 

I will use a node module based on libmbus
