### ISSUE TITLE
Fragen zum WM-Bus Adapter mit AES Geräten

### ISSUE THREAD

**Issue by chr-be** [soef/ioBroker.wm-bus#6]
Hallo,
ich habe Probeme mit dem Adapter Werte zu empfangen und mit ist nicht ganz klar, wie der Ablauf ist.
Die genaue Probelbeschreibung habe ich hier 
http://forum.iobroker.net/viewtopic.php?f=20&t=7037&p=73186#p73186
geposted.
Kannst Du da bitte mal drüberschauen?
VG, monty

**Comment by soef** [comment]
Hallo, ich kann so nicht viel erkennen. Bei den Log-Ausgaben handelt es sich um allgemeine Ausgaben für den Adapter. Schalte doch einmal in der Instanzen-Ansicht für den wm-bus Adapter die "Log Stufe" auf debug und poste die "Log" Ausgaben des wm-bus Adapter nach einem Neustart des Adapters.

Ich hoffe ich kann dir dann weiter helfen.

**Comment by chr-be** [comment]
danke für die schnelle Rückmeldung! ja, mach ich morgen - ich dachte ich hätte den Log auf Debug gestellt.
Der generelle Ablauf ist, wenn alles geht:
1. nur AES in Instanz eintragen und wenn dann einer der empfangenen Telegramme entschlüsselbar ist wird der Rest automatisch eingetragen und
2. und dann auch automatisch für den Messwert ein Objekt angelegt, dass dann in einem Ordner mit WM-Bus.0 oder so ähnlich auftaucht
Denke ich mir das richtig so?
Derzeit habe ich keine Objekte mit wm-bus.0 
VG, monty

**Comment by chr-be** [comment]
hilft das hier? 

`wm-bus.0	2017-06-28 21:19:04.186	debug	redis publish io.system.adapter.wm-bus.0.memHeapUsed {'val':11.74,'ack':true,'ts':1498677544174,'q':0,'from':'system.adapter.wm-bus.0','lc':1498677544174}
wm-bus.0	2017-06-28 21:19:04.186	debug	redis publish io.system.adapter.wm-bus.0.memHeapTotal {'val':17.99,'ack':true,'ts':1498677544169,'q':0,'from':'system.adapter.wm-bus.0','lc':1498677529168}
wm-bus.0	2017-06-28 21:19:04.186	debug	redis publish io.system.adapter.wm-bus.0.memRss {'val':32.79,'ack':true,'ts':1498677544167,'q':0,'from':'system.adapter.wm-bus.0','lc':1498677544167}
wm-bus.0	2017-06-28 21:19:04.185	debug	redis publish io.system.adapter.wm-bus.0.connected {'val':true,'ack':true,'ts':1498677544161,'q':0,'from':'system.adapter.wm-bus.0','lc':1498677529163}
wm-bus.0	2017-06-28 21:19:04.185	debug	redis publish io.system.adapter.wm-bus.0.alive {'val':true,'ack':true,'ts':1498677544159,'q':0,'from':'system.adapter.wm-bus.0','lc':1498677529162}
wm-bus.0	2017-06-28 21:18:49.180	debug	redis mget 1 1
wm-bus.0	2017-06-28 21:18:49.173	debug	redis publish io.system.adapter.wm-bus.0.outputCount {'val':8,'ack':true,'ts':1498677529173,'q':0,'from':'system.adapter.wm-bus.0','lc':1498646032871}
wm-bus.0	2017-06-28 21:18:49.172	debug	redis publish io.system.adapter.wm-bus.0.inputCount {'val':0,'ack':true,'ts':1498677529172,'q':0,'from':'system.adapter.wm-bus.0','lc':1498651771806}
wm-bus.0	2017-06-28 21:18:49.171	debug	redis publish io.system.adapter.wm-bus.0.uptime {'val':2,'ack':true,'ts':1498677529170,'q':0,'from':'system.adapter.wm-bus.0','lc':1498677529170}
wm-bus.0	2017-06-28 21:18:49.169	debug	redis publish io.system.adapter.wm-bus.0.memHeapUsed {'val':11.35,'ack':true,'ts':1498677529169,'q':0,'from':'system.adapter.wm-bus.0','lc':1498677529169}
wm-bus.0	2017-06-28 21:18:49.168	debug	redis publish io.system.adapter.wm-bus.0.memHeapTotal {'val':17.99,'ack':true,'ts':1498677529168,'q':0,'from':'system.adapter.wm-bus.0','lc':1498677529168}
wm-bus.0	2017-06-28 21:18:49.166	debug	redis publish io.system.adapter.wm-bus.0.memRss {'val':32.27,'ack':true,'ts':1498677529166,'q':0,'from':'system.adapter.wm-bus.0','lc':1498677529166}
wm-bus.0	2017-06-28 21:18:49.165	debug	redis publish io.system.adapter.wm-bus.0.connected {'val':true,'ack':true,'ts':1498677529163,'q':0,'from':'system.adapter.wm-bus.0','lc':1498677529163}
wm-bus.0	2017-06-28 21:18:49.162	debug	redis publish io.system.adapter.wm-bus.0.alive {'val':true,'ack':true,'ts':1498677529162,'q':0,'from':'system.adapter.wm-bus.0','lc':1498677529162}
wm-bus.0	2017-06-28 21:18:49.158	debug	redis keys 1 *.logging
wm-bus.0	2017-06-28 21:18:49.155	debug	redis psubscribe io.wm-bus.0.checkLogging
wm-bus.0	2017-06-28 21:18:49.139	info	starting. Version 0.2.0 in /opt/iobroker/node_modules/iobroker.wm-bus, node: v6.10.3
wm-bus.0	2017-06-28 21:18:49.095	debug	redis get system.adapter.wm-bus.0.alive ok: {'val':false,'ack':true,'ts':1498677524912,'q':0,'from':'system.host.ioBroker-RasPi','lc':1498677524872}
wm-bus.0	2017-06-28 21:18:49.078	info	States connected to redis 127.0.0.1:6379
wm-bus.0	2017-06-28 21:18:49.067	debug	statesDB connected
wm-bus.0	2017-06-28 21:18:49.016	debug	objectDB connected
wm-bus.0	2017-06-28 21:18:44.873	debug	redis publish io.system.adapter.wm-bus.0.alive {'val':false,'ack':true,'ts':1498677524872,'q':0,'from':'system.adapter.wm-bus.0','lc':1498677524872}
wm-bus.0	2017-06-28 21:18:44.865	info	going down...
wm-bus.0	2017-06-28 21:18:38.768	debug	redis publish io.system.adapter.wm-bus.0.outputCount {'val':8,'ack':true,'ts':1498677518767,'q':0,'from':'system.adapter.wm-bus.0','lc':1498646032871}`

**Comment by chr-be** [comment]
Hier noch mal vernünftig ...
> wm-bus.0	2017-06-29 09:19:32.619	debug	redis publish io.system.adapter.wm-bus.0.alive {"val":true,"ack":true,"ts":1498720772592,"q":0,"from":"system.adapter.wm-bus.0","lc":1498720757597}
wm-bus.0	2017-06-29 09:19:17.617	debug	redis mget 1 1
wm-bus.0	2017-06-29 09:19:17.609	debug	redis publish io.system.adapter.wm-bus.0.outputCount {"val":8,"ack":true,"ts":1498720757609,"q":0,"from":"system.adapter.wm-bus.0","lc":1498646032871}
wm-bus.0	2017-06-29 09:19:17.608	debug	redis publish io.system.adapter.wm-bus.0.inputCount {"val":0,"ack":true,"ts":1498720757607,"q":0,"from":"system.adapter.wm-bus.0","lc":1498651771806}
wm-bus.0	2017-06-29 09:19:17.606	debug	redis publish io.system.adapter.wm-bus.0.uptime {"val":2,"ack":true,"ts":1498720757606,"q":0,"from":"system.adapter.wm-bus.0","lc":1498720757606}
wm-bus.0	2017-06-29 09:19:17.605	debug	redis publish io.system.adapter.wm-bus.0.memHeapUsed {"val":11.36,"ack":true,"ts":1498720757604,"q":0,"from":"system.adapter.wm-bus.0","lc":1498720757604}
wm-bus.0	2017-06-29 09:19:17.603	debug	redis publish io.system.adapter.wm-bus.0.memHeapTotal {"val":17.99,"ack":true,"ts":1498720757603,"q":0,"from":"system.adapter.wm-bus.0","lc":1498720757603}
wm-bus.0	2017-06-29 09:19:17.602	debug	redis publish io.system.adapter.wm-bus.0.memRss {"val":32.07,"ack":true,"ts":1498720757601,"q":0,"from":"system.adapter.wm-bus.0","lc":1498720757601}
wm-bus.0	2017-06-29 09:19:17.600	debug	redis publish io.system.adapter.wm-bus.0.connected {"val":true,"ack":true,"ts":1498720757599,"q":0,"from":"system.adapter.wm-bus.0","lc":1498720757599}
wm-bus.0	2017-06-29 09:19:17.597	debug	redis publish io.system.adapter.wm-bus.0.alive {"val":true,"ack":true,"ts":1498720757597,"q":0,"from":"system.adapter.wm-bus.0","lc":1498720757597}
wm-bus.0	2017-06-29 09:19:17.594	debug	redis keys 1 *.logging
wm-bus.0	2017-06-29 09:19:17.590	debug	redis psubscribe io.wm-bus.0.checkLogging
wm-bus.0	2017-06-29 09:19:17.574	info	starting. Version 0.2.0 in /opt/iobroker/node_modules/iobroker.wm-bus, node: v6.10.3
wm-bus.0	2017-06-29 09:19:17.530	debug	redis get system.adapter.wm-bus.0.alive ok: {"val":false,"ack":true,"ts":1498720750717,"q":0,"from":"system.host.ioBroker-RasPi","lc":1498720750648}
wm-bus.0	2017-06-29 09:19:17.515	info	States connected to redis 127.0.0.1:6379
wm-bus.0	2017-06-29 09:19:17.504	debug	statesDB connected
wm-bus.0	2017-06-29 09:19:17.453	debug	objectDB connected
wm-bus.0	2017-06-29 09:19:10.651	info	terminating
wm-bus.0	2017-06-29 09:19:10.648	debug	redis publish io.system.adapter.wm-bus.0.alive {"val":false,"ack":true,"ts":1498720750648,"q":0,"from":"system.adapter.wm-bus.0","lc":1498720750648}
wm-bus.0	2017-06-29 09:19:10.643	info	going down...

**Comment by soef** [comment]
Hallo, ja, so wie du es denkst ist der Ablauf. Die Logausgaben sind aber immer noch nicht vom WM-Bus Adapter. Filtere doch in der Log-Ansicht (oben links in der ComboBox) einmal nach wm-bus.0. Wenn Daten empfangen wurden, müssten dort die Rohdaten in Hex auftauchen.

**Comment by chr-be** [comment]
hallo soef,
hab dir hier mal ein paar Screenshots von der Installation auf einem jungfreulichem Image gemacht. 
http://forum.iobroker.net/viewtopic.php?f=20&t=7037&p=73364#p73364
VG, monty

**Comment by chr-be** [comment]
Hallo soef,
habe mal den iM871A probiert und der bringt nach Adapter-Neustart drei Zeilen raw

> 

wm-bus.0 | 2017-07-15 07:56:13.423 | debug | raw: a58112260400e80700000000000000000000000000000000000000000000000000000000000005000700719c
-- | -- | -- | --
wm-bus.0 | 2017-07-15 07:56:13.414 | debug | raw: a5811008330013012b1e0000df9d
wm-bus.0 | 2017-07-15 07:56:11.403 | debug | raw: a5810617ff000200b32554101000010001ff0702320000000000002e86


danach kommt aber nichts mehr an raw sondern nur die üblichen Debugmeldungen. 

Als WM-Bus-Sender habe ich zwei von denen hier: http://download.innotas-elektronik.de/eurisii/eng/EHKV_EURISII_V2.4_ENG.pdf

**Comment by soef** [comment]
Hallo, im Moment kann ich dir leider nicht helfen. Kennst du die Manufacturer-ID (das sind drei Großbuchstaben)? Vielleicht hilft mir das.

**Comment by chr-be** [comment]
Auf Seite 17 ist der Telegrammaufbau vom Heizkostenzähler.  Der ist auf "T1 kurz" eingestellt und hat nur eine MeterID. 
https://irp-cdn.multiscreensite.com/0a3fa4dd/files/uploaded/Dokumentation_EURISII_DE.pdf

**Comment by chr-be** [comment]
was mir noch aufgefallen ist:
Habe zum Verstehen und Debuggen mal den Stick-Status abgefragt. 
Für T1 sollter der m.E. 3 sein. Als Antwort bringt der aber auch nach einem inti.Stick() immer 2?
Ist hier ggf. das Problem, das der iM871A mit den falschen Parametern arbeitet und so gar nits empfängt? 

`Com.prototype.init = function (callback) {
    var that = this;
    that.getConfig(function (err) {
        setTimeout(function () {
            that.initStick(function () {
                that.getInfo(function (err) {
                    that.getSysStatus(function (err) {
                    adapter.log.debug('INIT: SysStatus: ' + that.getSysStatus);
                        if ((that.hasOwnProperty('deviceConfig')) && (that.deviceConfig.linkMode !== that.LINKMODE_T1)) {
                            that.initStick();
                            
                            adapter.log.debug('INIT: LINKMODE: ' + that.deviceConfig.linkMode);
                            // trotz init 3 als Linkmode antwortet iM871A mit 2 ????
                            //??? xxxxxxx
                        }
                        if (callback) callback(soef.hasProp(that, 'deviceConfig.linkMode') ? 'iM871A' : undefined);
                        
                    });
                    adapter.log.debug('INIT2: LINKMODE : ' + that.deviceConfig.linkMode);
                });
            });
        }, 2000);
    });

};`

**Comment by soef** [comment]
Hallo, mit dem Telegrammaufbau kann man so auch nichts anfangen. Das W-Bus Protokoll ist schon etwas anders.

Du kannst aber einmal das W-Bus Studio herunterladen und den Stick testen und konfigurieren. Hier der Link: 
https://wireless-solutions.de/products/starterkits/sk-im871a.html
Auf der Seite den Downloadlink klicken und dann die unterste Zip-Datei.

Grüße.

**Comment by chr-be** [comment]
Hallo,
nun habe ich T1 über die Software vom iM871A eingestellt und empfange was ;-)
Bei der Auswertung läuft aber noch irgendwas falsch. Die bricht ab und der Adapter startet neu.

`wm-bus.0 | 2017-07-20 09:49:22.382 | error | ReferenceError: month is not defined
wm-bus.0 | 2017-07-20 09:49:22.381 | error | uncaught exception: month is not defined
wm-bus.0 | 2017-07-20 09:49:22.352 | debug | No. 6 type 4 at offset 35
wm-bus.0 | 2017-07-20 09:49:22.352 | debug | in DRH: type VIF_TIME_POINT_DATE_TIME

`

hier mal alles: 
`

wm-bus.0 | 2017-07-20 09:49:22.387 | info | going down...
-- | -- | -- | --
wm-bus.0 | 2017-07-20 09:49:22.382 | error | at SerialPort.raw (/opt/iobroker/node_modules/iobroker.wm-bus/node_modules/serialport/lib/parsers.js:7:13)
wm-bus.0 | 2017-07-20 09:49:22.382 | error | at SerialPort.emit (events.js:188:7)
wm-bus.0 | 2017-07-20 09:49:22.382 | error | at emitOne (events.js:96:13)
wm-bus.0 | 2017-07-20 09:49:22.382 | error | at Com.onData (/opt/iobroker/node_modules/iobroker.wm-bus/wm-bus.js:256:14)
wm-bus.0 | 2017-07-20 09:49:22.382 | error | at Com.decodeiM871A (/opt/iobroker/node_modules/iobroker.wm-bus/wm-bus.js:182:32)
wm-bus.0 | 2017-07-20 09:49:22.382 | error | at WMBUS.parse (/opt/iobroker/node_modules/iobroker.wm-bus/node_modules/wm-bus/lib/wmbus-decoder.js:1601:14)
wm-bus.0 | 2017-07-20 09:49:22.382 | error | at WMBUS.decodeApplicationLayer  (/opt/iobroker/node_modules/iobroker.wm-bus/node_modules/wm-bus/lib/wmbus-decoder.js:1548:17)
wm-bus.0 | 2017-07-20 09:49:22.382 | error | at WMBUS.decodePayload (/opt/iobroker/node_modules/iobroker.wm-bus/node_modules/wm-bus/lib/wmbus-decoder.js:1433:45)
wm-bus.0 | 2017-07-20 09:49:22.382 | error | at Object.valueCalcDateTime [as calcFunc]  (/opt/iobroker/node_modules/iobroker.wm-bus/node_modules/wm-bus/lib/wmbus-decoder.js:189:20)
wm-bus.0 | 2017-07-20 09:49:22.382 | error | at valueCalcDate (/opt/iobroker/node_modules/iobroker.wm-bus/node_modules/wm-bus/lib/wmbus-decoder.js:160:21)
wm-bus.0 | 2017-07-20 09:49:22.382 | error | ReferenceError: month is not defined
wm-bus.0 | 2017-07-20 09:49:22.381 | error | uncaught exception: month is not defined
wm-bus.0 | 2017-07-20 09:49:22.352 | debug | No. 6 type 4 at offset 35
wm-bus.0 | 2017-07-20 09:49:22.352 | debug | in DRH: type VIF_TIME_POINT_DATE_TIME
wm-bus.0 | 2017-07-20 09:49:22.351 | debug | type VIF_TIME_POINT_DATE_TIME bias 0 exp 0 valueFactor 1 unit
wm-bus.0 | 2017-07-20 09:49:22.350 | debug | match vifType VIF_TIME_POINT_DATE_TIME
wm-bus.0 | 2017-07-20 09:49:22.349 | debug | vifType VIF_TIME_POINT_DATE_TIME VIF 109 typeMask 127 type 109
wm-bus.0 | 2017-07-20 09:49:22.348 | debug | vifType VIF_TIME_POINT_DATE VIF 109 typeMask 127 type 108
wm-bus.0 | 2017-07-20 09:49:22.330 | debug | vifType VIF_PRESSURE VIF 109 typeMask 124 type 104
wm-bus.0 | 2017-07-20 09:49:22.328 | debug | vifType VIF_EXTERNAL_TEMP VIF 109 typeMask 124 type 100
wm-bus.0 | 2017-07-20 09:49:22.327 | debug | vifType VIF_TEMP_DIFF VIF 109 typeMask 124 type 96
wm-bus.0 | 2017-07-20 09:49:22.327 | debug | vifType VIF_RETURN_TEMP VIF 109 typeMask 124 type 92
wm-bus.0 | 2017-07-20 09:49:22.327 | debug | vifType VIF_FLOW_TEMP VIF 109 typeMask 124 type 88
wm-bus.0 | 2017-07-20 09:49:22.326 | debug | vifType VIF_MASS_FLOW VIF 109 typeMask 120 type 80
wm-bus.0 | 2017-07-20 09:49:22.326 | debug | vifType VIF_VOLUME_FLOW_EXT2 VIF 109 typeMask 120 type 72
wm-bus.0 | 2017-07-20 09:49:22.325 | debug | vifType VIF_VOLUME_FLOW_EXT1 VIF 109 typeMask 120 type 64
wm-bus.0 | 2017-07-20 09:49:22.325 | debug | vifType VIF_VOLUME_FLOW VIF 109 typeMask 120 type 56
wm-bus.0 | 2017-07-20 09:49:22.324 | debug | vifType VIF_THERMAL_POWER VIF 109 typeMask 120 type 48
wm-bus.0 | 2017-07-20 09:49:22.324 | debug | vifType VIF_ELECTRIC_POWER VIF 109 typeMask 120 type 40
wm-bus.0 | 2017-07-20 09:49:22.323 | debug | vifType VIF_OP_TIME_DAYS VIF 109 typeMask 127 type 39
wm-bus.0 | 2017-07-20 09:49:22.323 | debug | vifType VIF_OP_TIME_HOURS VIF 109 typeMask 127 type 38
wm-bus.0 | 2017-07-20 09:49:22.322 | debug | vifType VIF_OP_TIME_MIN VIF 109 typeMask 127 type 37
wm-bus.0 | 2017-07-20 09:49:22.322 | debug | vifType VIF_OP_TIME_SEC VIF 109 typeMask 127 type 36
wm-bus.0 | 2017-07-20 09:49:22.321 | debug | vifType VIF_ON_TIME_DAYS VIF 109 typeMask 127 type 35
wm-bus.0 | 2017-07-20 09:49:22.321 | debug | vifType VIF_ON_TIME_HOURS VIF 109 typeMask 127 type 34
wm-bus.0 | 2017-07-20 09:49:22.320 | debug | vifType VIF_ON_TIME_MIN VIF 109 typeMask 127 type 33
wm-bus.0 | 2017-07-20 09:49:22.319 | debug | vifType VIF_ON_TIME_SEC VIF 109 typeMask 127 type 32
wm-bus.0 | 2017-07-20 09:49:22.319 | debug | vifType VIF_MASS VIF 109 typeMask 120 type 24
wm-bus.0 | 2017-07-20 09:49:22.317 | debug | vifType VIF_VOLUME VIF 109 typeMask 120 type 16
wm-bus.0 | 2017-07-20 09:49:22.316 | debug | vifType VIF_ENERGY_JOULE VIF 109 typeMask 120 type 8
wm-bus.0 | 2017-07-20 09:49:22.315 | debug | vifType VIF_ENERGY_WATT VIF 109 typeMask 120 type 0
wm-bus.0 | 2017-07-20 09:49:22.315 | debug | vif: 6d isExtension 0
wm-bus.0 | 2017-07-20 09:49:22.314 | debug | offset in dif 1
wm-bus.0 | 2017-07-20 09:49:22.313 | debug | in DIF: datafield 4
wm-bus.0 | 2017-07-20 09:49:22.308 | debug | dif 4 storage 0
wm-bus.0 | 2017-07-20 09:49:22.307 | debug | Value raw 39570 value calc 395.70
wm-bus.0 | 2017-07-20 09:49:22.306 | debug | No. 5 type c at offset 29
wm-bus.0 | 2017-07-20 09:49:22.305 | debug | in DRH: type VIF_VOLUME
wm-bus.0 | 2017-07-20 09:49:22.291 | debug | type VIF_VOLUME bias -6 exp 4 valueFactor 0.01 unit mÂ³
wm-bus.0 | 2017-07-20 09:49:22.290 | debug | match vifType VIF_VOLUME
wm-bus.0 | 2017-07-20 09:49:22.290 | debug | vifType VIF_VOLUME VIF 20 typeMask 120 type 16
wm-bus.0 | 2017-07-20 09:49:22.289 | debug | vifType VIF_ENERGY_JOULE VIF 20 typeMask 120 type 8
wm-bus.0 | 2017-07-20 09:49:22.289 | debug | vifType VIF_ENERGY_WATT VIF 20 typeMask 120 type 0
wm-bus.0 | 2017-07-20 09:49:22.288 | debug | vif: 14 isExtension 0
wm-bus.0 | 2017-07-20 09:49:22.288 | debug | offset in dif 2
wm-bus.0 | 2017-07-20 09:49:22.287 | debug | in DIF: datafield c
wm-bus.0 | 2017-07-20 09:49:22.287 | debug | dife 1 extno 1 storage 32
wm-bus.0 | 2017-07-20 09:49:22.286 | debug | dif 8c storage 0
wm-bus.0 | 2017-07-20 09:49:22.286 | debug | Value raw 47554 value calc 47554000000
wm-bus.0 | 2017-07-20 09:49:22.285 | debug | No. 4 type c at offset 22
wm-bus.0 | 2017-07-20 09:49:22.281 | debug | in DRH: type VIF_ENERGY_JOULE
wm-bus.0 | 2017-07-20 09:49:22.281 | debug | type VIF_ENERGY_JOULE bias 0 exp 6 valueFactor 1000000 unit J
wm-bus.0 | 2017-07-20 09:49:22.280 | debug | match vifType VIF_ENERGY_JOULE
wm-bus.0 | 2017-07-20 09:49:22.279 | debug | vifType VIF_ENERGY_JOULE VIF 14 typeMask 120 type 8
wm-bus.0 | 2017-07-20 09:49:22.279 | debug | vifType VIF_ENERGY_WATT VIF 14 typeMask 120 type 0
wm-bus.0 | 2017-07-20 09:49:22.278 | debug | vif: e isExtension 0
wm-bus.0 | 2017-07-20 09:49:22.277 | debug | offset in dif 2
wm-bus.0 | 2017-07-20 09:49:22.277 | debug | in DIF: datafield c
wm-bus.0 | 2017-07-20 09:49:22.276 | debug | dife 1 extno 1 storage 32
wm-bus.0 | 2017-07-20 09:49:22.275 | debug | dif 8c storage 0
wm-bus.0 | 2017-07-20 09:49:22.274 | debug | Value raw 18025 value calc 18025000000
wm-bus.0 | 2017-07-20 09:49:22.273 | debug | No. 3 type c at offset 15
wm-bus.0 | 2017-07-20 09:49:22.272 | debug | in DRH: type VIF_ENERGY_JOULE
wm-bus.0 | 2017-07-20 09:49:22.272 | debug | type VIF_ENERGY_JOULE bias 0 exp 6 valueFactor 1000000 unit J
wm-bus.0 | 2017-07-20 09:49:22.271 | debug | match vifType VIF_ENERGY_JOULE
wm-bus.0 | 2017-07-20 09:49:22.270 | debug | vifType VIF_ENERGY_JOULE VIF 14 typeMask 120 type 8
wm-bus.0 | 2017-07-20 09:49:22.270 | debug | vifType VIF_ENERGY_WATT VIF 14 typeMask 120 type 0
wm-bus.0 | 2017-07-20 09:49:22.269 | debug | vif: e isExtension 0
wm-bus.0 | 2017-07-20 09:49:22.268 | debug | offset in dif 1
wm-bus.0 | 2017-07-20 09:49:22.268 | debug | in DIF: datafield c
wm-bus.0 | 2017-07-20 09:49:22.267 | debug | dif 4c storage 1
wm-bus.0 | 2017-07-20 09:49:22.266 | debug | Value raw 39736 value calc 397.36
wm-bus.0 | 2017-07-20 09:49:22.263 | debug | No. 2 type c at offset 9
wm-bus.0 | 2017-07-20 09:49:22.262 | debug | in DRH: type VIF_VOLUME
wm-bus.0 | 2017-07-20 09:49:22.261 | debug | type VIF_VOLUME bias -6 exp 4 valueFactor 0.01 unit mÂ³
wm-bus.0 | 2017-07-20 09:49:22.257 | debug | match vifType VIF_VOLUME
wm-bus.0 | 2017-07-20 09:49:22.256 | debug | vifType VIF_VOLUME VIF 20 typeMask 120 type 16
wm-bus.0 | 2017-07-20 09:49:22.255 | debug | vifType VIF_ENERGY_JOULE VIF 20 typeMask 120 type 8
wm-bus.0 | 2017-07-20 09:49:22.253 | debug | vifType VIF_ENERGY_WATT VIF 20 typeMask 120 type 0
wm-bus.0 | 2017-07-20 09:49:22.252 | debug | vif: 14 isExtension 0
wm-bus.0 | 2017-07-20 09:49:22.251 | debug | offset in dif 1
wm-bus.0 | 2017-07-20 09:49:22.250 | debug | in DIF: datafield c
wm-bus.0 | 2017-07-20 09:49:22.249 | debug | dif c storage 0
wm-bus.0 | 2017-07-20 09:49:22.247 | debug | Value raw 47677 value calc 47677000000
wm-bus.0 | 2017-07-20 09:49:22.245 | debug | No. 1 type c at offset 3
wm-bus.0 | 2017-07-20 09:49:22.244 | debug | in DRH: type VIF_ENERGY_JOULE
wm-bus.0 | 2017-07-20 09:49:22.243 | debug | type VIF_ENERGY_JOULE bias 0 exp 6 valueFactor 1000000 unit J
wm-bus.0 | 2017-07-20 09:49:22.241 | debug | match vifType VIF_ENERGY_JOULE
wm-bus.0 | 2017-07-20 09:49:22.240 | debug | vifType VIF_ENERGY_JOULE VIF 14 typeMask 120 type 8
wm-bus.0 | 2017-07-20 09:49:22.239 | debug | vifType VIF_ENERGY_WATT VIF 14 typeMask 120 type 0
wm-bus.0 | 2017-07-20 09:49:22.236 | debug | vif: e isExtension 0
wm-bus.0 | 2017-07-20 09:49:22.230 | debug | offset in dif 1
wm-bus.0 | 2017-07-20 09:49:22.229 | debug | in DIF: datafield c
wm-bus.0 | 2017-07-20 09:49:22.228 | debug | dif c storage 0
wm-bus.0 | 2017-07-20 09:49:22.224 | debug | skipping filler at offset 1 of 60
wm-bus.0 | 2017-07-20 09:49:22.222 | debug | skipping filler at offset 0 of 60
wm-bus.0 | 2017-07-20 09:49:22.210 | debug | short header
wm-bus.0 | 2017-07-20 09:49:22.209 | debug | 7a7a0000002f2f0c0e777604000c14369703004c0e258001008c010e547504008c011470950300046d0f08342702fd17000084016d00002127446d0000e1f193cd
wm-bus.0 | 2017-07-20 09:49:22.202 | debug | calc len 83, actual 75
wm-bus.0 | 2017-07-20 09:49:22.200 | debug | lfield 72
wm-bus.0 | 2017-07-20 09:49:22.191 | debug | raw:  a582034844a7325649376804047a7a0000002f2f0c0e777604000c14369703004c0e258001008c010e547504008c011470950300046d0f08342702fd17000084016d00002127446d0000e1f193cd
wm-bus.0 | 2017-07-20 09:49:10.479 | debug | raw: a58112260400834f05000000000000000000000000000000000080010000000000007c0000000500070054b5
wm-bus.0 | 2017-07-20 09:49:10.454 | debug | raw: a5811008330013012b1e0000df9d
wm-bus.0 | 2017-07-20 09:49:08.437 | debug | raw: a5810617ff000400b32554101000010001ff07023200000007000c2f73
wm-bus.0 | 2017-07-20 09:49:08.344 | debug | redis mget 1 1
wm-bus.0 | 2017-07-20 09:49:08.320 | debug | redis publish io.system.adapter.wm-bus.0.outputCount  {"val":8,"ack":true,"ts":1500536948319,"q":0,"from":"system.adapter.wm-bus.0","lc":1499418845430}
wm-bus.0 | 2017-07-20 09:49:08.318 | debug | redis publish io.system.adapter.wm-bus.0.inputCount  {"val":0,"ack":true,"ts":1500536948317,"q":0,"from":"system.adapter.wm-bus.0","lc":1500533533999}
wm-bus.0 | 2017-07-20 09:49:08.315 | debug | redis publish io.system.adapter.wm-bus.0.uptime  {"val":3,"ack":true,"ts":1500536948314,"q":0,"from":"system.adapter.wm-bus.0","lc":1500536729723}
wm-bus.0 | 2017-07-20 09:49:08.312 | debug | redis publish io.system.adapter.wm-bus.0.memHeapUsed  {"val":11.37,"ack":true,"ts":1500536948311,"q":0,"from":"system.adapter.wm-bus.0","lc":1500536948311}
wm-bus.0 | 2017-07-20 09:49:08.309 | debug | redis publish io.system.adapter.wm-bus.0.memHeapTotal  {"val":17.99,"ack":true,"ts":1500536948308,"q":0,"from":"system.adapter.wm-bus.0","lc":1500533533990}
wm-bus.0 | 2017-07-20 09:49:08.306 | debug | redis publish io.system.adapter.wm-bus.0.memRss  {"val":32.37,"ack":true,"ts":1500536948306,"q":0,"from":"system.adapter.wm-bus.0","lc":1500536948306}
wm-bus.0 | 2017-07-20 09:49:08.303 | debug | redis publish io.system.adapter.wm-bus.0.connected  {"val":true,"ack":true,"ts":1500536948300,"q":0,"from":"system.adapter.wm-bus.0","lc":1500536948300}
wm-bus.0 | 2017-07-20 09:49:08.298 | debug | redis publish io.system.adapter.wm-bus.0.alive  {"val":true,"ack":true,"ts":1500536948297,"q":0,"from":"system.adapter.wm-bus.0","lc":1500536948297}
wm-bus.0 | 2017-07-20 09:49:08.291 | debug | redis keys 1 *.logging
wm-bus.0 | 2017-07-20 09:49:08.285 | debug | redis psubscribe io.wm-bus.0.checkLogging
wm-bus.0 | 2017-07-20 09:49:08.255 | info | starting. Version 0.2.0 in /opt/iobroker/node_modules/iobroker.wm-bus, node: v6.11.0
wm-bus.0 | 2017-07-20 09:49:08.174 | debug | redis get system.adapter.wm-bus.0.alive ok:  {"val":false,"ack":true,"ts":1500536914953,"q":0,"from":"system.host.ioBroker-RasPi","lc":1500536914793}
wm-bus.0 | 2017-07-20 09:49:08.141 | info | States connected to redis 127.0.0.1:6379
wm-bus.0 | 2017-07-20 09:49:08.120 | debug | statesDB connected
wm-bus.0 | 2017-07-20 09:49:08.020 | debug | objectDB connected
wm-bus.0 | 2017-07-20 09:48:34.904 | info | terminating
wm-bus.0 | 2017-07-20 09:48:34.794 | debug | redis publish io.system.adapter.wm-bus.0.alive  {"val":false,"ack":true,"ts":1500536914793,"q":0,"from":"system.adapter.wm-bus.0","lc":1500536914793}
wm-bus.0 | 2017-07-20 09:48:34.782 | info | going down...

`

**Comment by soef** [comment]
Hello, oh, this bug in the wm-bus module has been fixed month ago. Bud ioBroker.wm-bus still uses the old version. Now, in Version 0.2.2, the adapter requires the new version and your problem shoult be solved.
