### ISSUE TITLE
iM871A empfangen wohl was aber dann gehts nicht weiter.

### ISSUE THREAD

**Issue by HansPeterMeier** [soef/ioBroker.wm-bus#9]
Hallo soef,
ich habe mir neue Wärmemengenzähler eingebaut und gleich die mit WM-Bus genommen in der Hoffnung, dass ich die Werte mitloggen kann.
Ich besitze folgende Hardware.
1. Engelmann Sensostar http://www.engelmann.de/wp-content/uplo ... _S3_de.pdf
2. iM871A mit der Software Wireless M Studio
3. iobroker auf Orange Pi plus 2E, alles auf dem aktuellen Stand.

Den Adapter konnte ich soweit installieren. Nachdem ich den Stick auf Link Mode T1 umgestellt hatte, kamen im Adapter auch die Seriennummer rüber.
Nach der Errormessage "encrypted message and no aeskey provided. Enter the aeskey in the settings." habe ich die AES Schlüssel von "Messhelden" eingetragen.

Nun scheint da was zu kommen, aber meckert wohl weil die Länge des Schlüssel falsch wäre.

Hast du eine Idee??
http://forum.iobroker.net/viewtopic.php?f=20&t=8330&p=88450#p88450
`host.orangepiplus2e   2017-10-04 19:22:46.705   info   Restart adapter system.adapter.wm-bus.0 because enabled
host.orangepiplus2e   2017-10-04 19:22:46.705   error   instance system.adapter.wm-bus.0 terminated with code 0 (OK)
Caught   2017-10-04 19:22:46.704   error   by controller[0]: at SerialPort.emit (events.js:188:7)
Caught   2017-10-04 19:22:46.704   error   by controller[0]: at emitOne (events.js:96:13)
Caught   2017-10-04 19:22:46.704   error   by controller[0]: at Com.onData (/opt/iobroker/node_modules/iobroker.wm-bus/wm-bus.js:256:14)
Caught   2017-10-04 19:22:46.704   error   by controller[0]: at Com.decodeiM871A (/opt/iobroker/node_modules/iobroker.wm-bus/wm-bus.js:182:32)
Caught   2017-10-04 19:22:46.703   error   by controller[0]: at WMBUS.parse (/opt/iobroker/node_modules/iobroker.wm-bus/node_modules/wm-bus/lib/wmbus-decoder.js:1612:14)
Caught   2017-10-04 19:22:46.703   error   by controller[0]: at WMBUS.decodeApplicationLayer (/opt/iobroker/node_modules/iobroker.wm-bus/node_modules/wm-bus/lib/wmbus-decoder.js:1532:28)
Caught   2017-10-04 19:22:46.703   error   by controller[0]: at WMBUS.decrypt (/opt/iobroker/node_modules/iobroker.wm-bus/node_modules/wm-bus/lib/wmbus-decoder.js:1253:29)
Caught   2017-10-04 19:22:46.702   error   by controller[0]: at Object.Decipheriv (crypto.js:239:12)
Caught   2017-10-04 19:22:46.702   error   by controller[0]: at new Decipheriv (crypto.js:242:16)
Caught   2017-10-04 19:22:46.700   error   by controller[0]: at Error (native)
Caught   2017-10-04 19:22:46.687   error   by controller[0]: Error: Invalid key length
wm-bus.0   2017-10-04 19:22:46.563   info   going down...
wm-bus.0   2017-10-04 19:22:46.559   error   at SerialPort.emit (events.js:188:7)
wm-bus.0   2017-10-04 19:22:46.559   error   at emitOne (events.js:96:13)
wm-bus.0   2017-10-04 19:22:46.559   error   at Com.onData (/opt/iobroker/node_modules/iobroker.wm-bus/wm-bus.js:256:14)
wm-bus.0   2017-10-04 19:22:46.559   error   at Com.decodeiM871A (/opt/iobroker/node_modules/iobroker.wm-bus/wm-bus.js:182:32)
wm-bus.0   2017-10-04 19:22:46.559   error   at WMBUS.parse (/opt/iobroker/node_modules/iobroker.wm-bus/node_modules/wm-bus/lib/wmbus-decoder.js:1612:14)
wm-bus.0   2017-10-04 19:22:46.559   error   at WMBUS.decodeApplicationLayer (/opt/iobroker/node_modules/iobroker.wm-bus/node_modules/wm-bus/lib/wmbus-decoder.js:1532:28)
wm-bus.0   2017-10-04 19:22:46.559   error   at WMBUS.decrypt (/opt/iobroker/node_modules/iobroker.wm-bus/node_modules/wm-bus/lib/wmbus-decoder.js:1253:29)
wm-bus.0   2017-10-04 19:22:46.559   error   at Object.Decipheriv (crypto.js:239:12)
wm-bus.0   2017-10-04 19:22:46.559   error   at new Decipheriv (crypto.js:242:16)
wm-bus.0   2017-10-04 19:22:46.559   error   at Error (native)
wm-bus.0   2017-10-04 19:22:46.559   error   Error: Invalid key length
wm-bus.0   2017-10-04 19:22:46.558   error   uncaught exception: Invalid key length
wm-bus.0   2017-10-04 19:22:46.525   debug   short header
wm-bus.0   2017-10-04 19:22:46.524   debug   7a27003025a1267e39e163869edfa99130b94b0f98b482a093e9e9d91ffc50b1fb431c97b80d207add31dfb87f136d975b895d457b03fd0c05010002fd0b2011decf
wm-bus.0   2017-10-04 19:22:46.520   debug   calc len 84, actual 76
wm-bus.0   2017-10-04 19:22:46.518   debug   lfield 73
wm-bus.0   2017-10-04 19:22:46.456   debug   raw: a58203494421046840157300047a27003025a1267e39e163869edfa99130b94b0f98b482a093e9e9d91ffc50b1fb431c97b80d207add31dfb87f136d975b895d457b03fd0c05010002fd0b2011decf
wm-bus.0   2017-10-04 19:19:56.291   debug   raw: a58112260400daba03000000000000000000000000000000000004000000000000000100000005000700e9a3
wm-bus.0   2017-10-04 19:19:56.285   debug   raw: a5811008330013011d210000de56
wm-bus.0   2017-10-04 19:19:54.279   debug   raw: a5810617ff000300b32557101000010001ff0702320000000000005381
wm-bus.0   2017-10-04 19:19:54.004   info   starting. Version 0.2.5 in /opt/iobroker/node_modules/iobroker.wm-bus, node: v6.11.2
wm-bus.0   2017-10-04 19:19:53.910   debug   statesDB connected
wm-bus.0   2017-10-04 19:19:53.742   debug   objectDB connected`

**Comment by soef** [comment]
Hallo, 
crypto: Invalid key length 
Wie lang ist denn der AES-Schlüssel den du verwendest. Er müsste 16 Zeichen lang sein.

**Comment by HansPeterMeier** [comment]
Hi, also, meine AES Keys sind 32 Zeichen lang.

**Comment by soef** [comment]
Hi, kann es sein, das es sich dabei um jeweils zweistellige Hexwerte handelt? Also z.B.:
30313233343536373839414243444546 -> 0123456789ABCDEF
  0  1  2  3  4  5  6  7  8  9 A  B  C  D E  F

**Comment by HansPeterMeier** [comment]
Erstmal vielen Dank für deine Unterstützung.
Hier mal ein key von einem Zähler.
AES-Key: 87A549E85E88A4BFDB6CD7CAD1541706

Kannst du damit was anfangen?
Gruß

**Comment by soef** [comment]
Ist das der passende Key zu den Rohdaten oben in deinem Log? Wenn ich deinen Key auf 16 Byte umrechne,  passt der key nicht zu den Rohdaten. Wrong key!
Ansonsten gebe mir doch einmal die Rohdaten (im Log raw: xxxxxx) passend zu diesem Key.

**Comment by HansPeterMeier** [comment]
Sorry, hätte da ein paar mehr Informationen zu geben sollen. Ich besitze 2 Zähler, die Seriennummer kommt such schon rein.
Hier die keys zu den Zähler
Zähler-Seriennummer: 73154067
AES-Key: 87A549E85E88A4BFDB6CD7CAD1541706

Zähler-Seriennummer: 73154068
AES-Key: 4A3299FF18CA6C63838285668C99189

**Comment by soef** [comment]
Hallo, bei dem letzte AES-Key fehlt ein Zeichen. Er ist nur 31 Zeichen lang.

**Comment by HansPeterMeier** [comment]
Oh ja, da muss noch eine 7 hinten dran. Sorry.

**Comment by soef** [comment]
Deine beiden Geräte sollten nun mit der Version 0.2.6 funktionieren.

**Comment by HansPeterMeier** [comment]
![bildschirmfoto 2017-10-16 um 19 28 18](https://user-images.githubusercontent.com/32676715/31625998-6293b90c-b2a8-11e7-94ce-fe10e3b423f5.png)

Vielen Vielen Dank für deine Ergänzung meiner Wärmezähler, scheint soweit alles zu laufen, nur die Bezeichnung der Units sind mit ein paar Sonderzeichen verunstaltet, aber stört erst mal weiter nicht.

**Comment by soef** [comment]
Die Sonderzeichen sollten nun in der Version 0.2.7 och richtig angezeigt werden.

**Comment by HansPeterMeier** [comment]
Beim dem Temperaturen ist leider noch ein Sonderzeichen drin.
Müsste "VIF_ELECTRIC_POWER" nicht ein Channel sein? ist dort in den Objekten noch ein State.
Werden auch Nachkommastellen angezeigt? Bei Temperaturdifferenz zeigt er bei gleichen Vor und Rücklauf was mit 655,18 an, das passt ja nicht
Eine Frage generell, sind das die reinen Rohdaten oder musst du die noch irgendwie aufbereiten.


Gruß und vielen Dank für deine Mühe.

![bildschirmfoto 2017-10-17 um 20 16 56](https://user-images.githubusercontent.com/32676715/31736573-726142ca-b445-11e7-8181-37b355af3845.png)

![bildschirmfoto 2017-10-18 um 20 39 16](https://user-images.githubusercontent.com/32676715/31736458-2154cfa0-b445-11e7-83b2-9c92ec4bd4d4.png)

**Comment by soef** [comment]
Tiefere Ebenen (müsste ... nicht ein channel sein) gibt es meines Wissens nicht. Nachkommastellen usw. werden durch das wm-bus Protokoll bestimmt. Wenn du meinst, das da etwas nicht korrekt ist, gebe mir einmal die Roh-Daten aus dem Log und den Index des Datenpunktes.

Die falschen Zeichen der Einheiten sind in 0.2.8 korrigiert. War ein utf8 Problem.

**Comment by HansPeterMeier** [comment]
Zeichen passen jetzt soweit, nur jetzt fehlt der Durchflusswert im Datenpunkt 5
![bildschirmfoto 2017-10-20 um 19 24 41](https://user-images.githubusercontent.com/32676715/31835043-69d8605c-b5d0-11e7-96b7-50d19eb623f1.png)

und bei der Temperaturdifferenz steht immer irgend ne großer Wert, wenn Vorlauf und Rücklauf beinahe gleich sind.
![bildschirmfoto 2017-10-20 um 19 24 56](https://user-images.githubusercontent.com/32676715/31835070-82203662-b5d0-11e7-9c72-983140eb15af.png)

**Comment by soef** [comment]
Kannst Du mir einmal die Raw: Daten aus dem Log geben, damit ich das nachvollziehen kann?

**Comment by HansPeterMeier** [comment]
reicht das?
[untitled.txt](https://github.com/soef/ioBroker.wm-bus/files/1403006/untitled.txt)

**Comment by HansPeterMeier** [comment]
Das mit dem Durchflusswert in Datenpunkt 5 nehme ich zurück. Da kommt nun was rein.
Da bleibt nur noch die hohe Tempdifferenz, denke aber schon fast, dass es vom Zähler selber kommt.

**Comment by soef** [comment]
Das reicht. Es wurde einfach nur die falsche Einheit verwendet. die Angabe ist nicht in K(elvin) sondern in 
1/1000 K also mK.
Die Einheit ist in Version 0.2.9 angepasst.

**Comment by HansPeterMeier** [comment]
Passt soweit alles. Mal schauen wann ich die Wasserzähler mit dem WM-Bus Aufsatz bestücke. Mal schauen was die so funken.
Vielen Vielen Dank für deine Hilfe.

**Comment by HansPeterMeier** [comment]
Sorry, ich muss mich noch mal melden, bei einem Zähler von den beiden ist die Tempdiff ab und zu immer noch so hoch. Das ist aber nicht immer so.
![bildschirmfoto 2017-10-23 um 19 46 34](https://user-images.githubusercontent.com/32676715/31904346-45fcc468-b82b-11e7-8b26-fd264cd7ea9d.png)

Dann hätte ich noch eine Kleinigkeit.
in DP 6 Ordner steht direkt 0,00W, jedoch im Unterverzeichnis unter value 4372W. Eigentlich waren die immer gleich. Nach dem Zeitstempel zu urteilen wurde der Value Wert nicht aktualisiert und trägt den Wert der 2. Messung vorher. Ist das nachvollziehbar oder kommt das vom Zähler selber irgendwie.

![bildschirmfoto 2017-10-23 um 19 55 41](https://user-images.githubusercontent.com/32676715/31904818-9519f6f0-b82c-11e7-8693-c0131426b8aa.png)

Gruß

**Comment by LastPerfectTobi** [comment]
> Sorry, hätte da ein paar mehr Informationen zu geben sollen. Ich besitze 2 Zähler, die Seriennummer kommt such schon rein.
> 
> Hier die keys zu den Zähler
> 
> Zähler-Seriennummer: 73154067
> 
> AES-Key: 87A549E85E88A4BFDB6CD7CAD1541706
> 
> 
> 
> Zähler-Seriennummer: 73154068
> 
> AES-Key: 4A3299FF18CA6C63838285668C99189

Wie lässt sich denn aus der Seriennummer der Key berechnen? 
Hab vier Zähler die ich gerne automatisiert auslesen würde, aber kenne den Key nicht. 
Kannst du mir da helfen?

**Comment by dominikde** [comment]
@LastPerfectTobi bist Du hier weitergekommen? Wenn ich es richtig sehe sind die Zähler mit dem Standard-Master-Key von Engelmann versehen, ist das richtig? Bzw. wo bekomme ich den her?

**Comment by LastPerfectTobi** [comment]
> @LastPerfectTobi bist Du hier weitergekommen? Wenn ich es richtig sehe sind die Zähler mit dem Standard-Master-Key von Engelmann versehen, ist das richtig? Bzw. wo bekomme ich den her?

Leider Nein. 
Ich kann mit dem Stick und dem Adapter Daten empfangen, aber die Zählerwerte können wirklich nur mit dem Master-Key ausgelesen werden. 
Der Versorger/Betreiber des Zähler hat diesen natürlich, da man damit aber auch den Zähler umprogrammieren kann (und somit die Verbrauchswerte manipulieren könnte) wird man den nicht ausgehändigt bekommen.
